on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
  b:
    runs-on: ubuntu-latest
    needs: [a]
    steps:
      - run: |
          ls $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
