name: Workflow with containers

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sxs-container.yaml"

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      cosmos:
        # Docker Hub image
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        options: >-
          --memory 3g
          --cpus=2.0
          --tty
          --interactive
          --health-cmd "if [[ $(ps aux | grep './cosmosdb-emulator' | wc -l) = 3 ]]; then exit 0; else exit 1; fi"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8081:8081
        env:
          AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
          AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true

    steps:
      - run: |
          echo Checking if cosmos is up
          curl -vskf http://cosmos:8081/_explorer/emulator.pem > emulator.pem
          ls
